CREATE DATABASE QUANLYSINHVIEN_PTTK
USE QUANLYSINHVIEN_PTTK

--- LỚP: NGƯỜI
CREATE TABLE NGUOI (
	ID NCHAR(100) PRIMARY KEY,
	TEN NVARCHAR(100),
	NGAYSINH DATE
);

--- LỚP: KHOA
CREATE TABLE KHOA (
	MAKHOA NCHAR(100) PRIMARY KEY,
	TENKHOA NVARCHAR(100),
);

--- LỚP: NGÀNH
CREATE TABLE NGANH (
	MAKHOA NCHAR(100) FOREIGN KEY REFERENCES KHOA(MAKHOA),
	MANGANH NCHAR(100) PRIMARY KEY,
	TENNGANH NVARCHAR(100)
);

--- LỚP: MÔN HỌC
CREATE TABLE MONHOC (
	MAMH NCHAR(100) PRIMARY KEY,
	TENMH NVARCHAR(100),
	TINCHI INT
);

--- LỚP: SINH VIÊN
CREATE TABLE SINHVIEN (
	ID NCHAR(100) FOREIGN KEY REFERENCES NGUOI(ID),
	MASV NCHAR(100) PRIMARY KEY,
	LOP NVARCHAR(100),
	MANGANH NCHAR(100) FOREIGN KEY REFERENCES NGANH(MANGANH),
	KHOAHOC INT
);

--- LỚP: THẺ SINH VIÊN
CREATE TABLE THESINHVIEN (
	MATHE NCHAR(100) PRIMARY KEY,
	MASV NCHAR(100) FOREIGN KEY REFERENCES SINHVIEN(MASV),
	MANGANH NCHAR(100) FOREIGN KEY REFERENCES NGANH(MANGANH),
);

--- LỚP: NHÂN VIÊN
CREATE TABLE NHANVIEN (
	ID NCHAR(100) FOREIGN KEY REFERENCES NGUOI(ID),
	MANHANVIEN NCHAR(100) PRIMARY KEY,
	MATKHAU CHAR(100),
	VAITRO NVARCHAR(100),
	FOREIGN KEY(ID) REFERENCES NGUOI(ID)
);

--- LỚP: HỒ SƠ
CREATE TABLE HOSO (
	MAHOSO NCHAR(100) PRIMARY KEY,
	TENHOSO NVARCHAR(100),
	THONGTIN NVARCHAR(100),
	GHICHU NVARCHAR(100),
	MANHANVIEN NCHAR(100) FOREIGN KEY REFERENCES NHANVIEN(MANHANVIEN), --- THÔNG TIN NGƯỜI TẠO HỒ SƠ
);
